Comparison of Flaveria trinervia and Flaveria pringlei
========================================================

```{r load_data}
setwd('~/hydrogen/flaveria/Fp/Fp_2')
fp <- read.csv('Fp_express.tpm', sep="\t", head=T)
key <- read.csv('key_agi.txt',sep='\t', head=F)
names(key) <- c("annotation", "description")

setwd('~/hydrogen/flaveria/Ft/Ft_2')
ft <- read.csv('Ft_express.tpm', sep="\t", head=T)

setwd('~/hydrogen/flaveria/robin')
anno <- read.csv('robin_11.txt', sep="\t", head=F)
names(anno) <- c("species", "contig", "annotation")
anno$species <- gsub(anno$species, pattern="_200", replacement="")
```

```{r prep, fig.width=12, fig.height=12}
library(plyr)
library(reshape2)
library(ggplot2)
fp_anno <- anno[which(anno$species=="Fp"),]
ft_anno <- anno[which(anno$species=="Ft"),]

fp_2 <- merge(fp, fp_anno, by.x="contig", by.y="contig")     # merge tpm data and annotation from rrobin
fp_2 <- fp_2[,-c(2, 21,22)]
key_fp <- fp_2[which(fp_2$annotation %in% key$annotation),] # select only data that is key
fp_tpm <- ddply(key_fp, .(annotation), numcolwise(sum))        # sum columns, grouping by annotation

ft_2 <- merge(ft, ft_anno, by.x="contig", by.y="contig")
ft_2 <- ft_2[,-c(2, 21,22)]
key_ft <- ft_2[which(ft_2$annotation %in% key$annotation),]
ft_tpm <- ddply(key_ft, .(annotation), numcolwise(sum))        # sum columns, grouping by annotation

fp_melt <- melt(fp_tpm)
ft_melt <- melt(ft_tpm)
fp_melt$variable <- gsub(fp_melt$variable, pattern="F[a-z]_[0-9].", replacement="")
ft_melt$variable <- gsub(ft_melt$variable, pattern="F[a-z]_[0-9].", replacement="")

fp_sum <- ddply(fp_melt, .(annotation,variable), numcolwise(sum)) # do i need to do this sum again?
ft_sum <- ddply(ft_melt, .(annotation,variable), numcolwise(sum))

both <- merge(fp_sum, ft_sum, by=c("annotation","variable"))
names(both) <- c("annotation","section","Fp","Ft")
```

```{r scatter_plot_loop, fig.width=12, fig.height=12}
setwd("~/hydrogen/flaveria")
agis <- key[which(key$annotation %in% both$annotation),]

for (i in 1:nrow(agis)) { # 
  print(i)
  tmp <- both[which(both$annotation==paste(agis[i,"annotation"])),]
  c<-ggplot(tmp, aes(x = Fp, y = Ft, group=annotation)) +
     geom_point(size = 2) +
     geom_path() +
     geom_text(aes(label=section)) +
     coord_fixed(ratio = 1, xlim=c(0,max(tmp$Fp,tmp$Ft)), ylim=c(0,max(tmp$Fp,tmp$Ft))) +
     ggtitle(paste("Trinervia Pringlei comparison of ", agis[i,"annotation"], " ", agis[i,"description"]))
   print(c)
}

```
